### ISSUE TITLE
Run cursor help is not working

### ISSUE THREAD

**Issue by hauchu1196** [yuaotian/go-cursor-help#11]
### Description
The application is not working.

### Environment Details
- Version: 0.43.5
- VSCode Version: 1.93.1
- Commit: 2eaa79a1b14ccff5d1c78a2c358a08be16a8e5a0
- Date: 2024-11-27T09:11:51.854Z
- Electron: 30.5.1
- Chromium: 124.0.6367.243
- Node.js: 20.16.0
- V8: 12.4.254.20-electron.0
- OS: Darwin arm64 23.6.0

![Screenshot 2024-12-11 at 11 25 2
![Screenshot 2024-12-11 at 11 25 31](https://github.com/user-attachments/assets/0f46db29-9d65-4c9a-ba75-db556edc895e)
2](https://github.com/user-attachments/assets/7552d3b0-9540-4664-9c1b-222fed05cf23)

**Comment by hauchu1196** [comment]
![Screenshot 2024-12-11 at 11 25 59](https://github.com/user-attachments/assets/fad37960-db0c-4beb-a8fe-11630a54804c)

**Comment by yuaotianAI** [comment]
Hi, you can try it with the new version~

**Comment by hauchu1196** [comment]
@yuaotianAI i try it with new version but still not working
![Screenshot 2024-12-11 at 15 36 03](https://github.com/user-attachments/assets/e7b79c2b-5a4f-457c-ac1b-1eeb74cbdbb2)
![Screenshot 2024-12-11 at 15 36 09](https://github.com/user-attachments/assets/c57c2ad5-eb85-4a32-829f-0e3760c62160)

**Comment by NguyenManhThuyen123** [comment]
> @yuaotianAI i try it with new version but still not working ![Screenshot 2024-12-11 at 15 36 03](https://private-user-images.githubusercontent.com/19184658/394643565-e7b79c2b-5a4f-457c-ac1b-1eeb74cbdbb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDc0ODMsIm5iZiI6MTczMzkwNzE4MywicGF0aCI6Ii8xOTE4NDY1OC8zOTQ2NDM1NjUtZTdiNzljMmItNWE0Zi00NTdjLWFjMWItMWVlYjc0Y2JkYmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA4NTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NjY3NTI5MjQyZGMyNzMwZTRhYzZkMTAzZjllZjEwMzhjMGFiZWJlYWY0NTcyOGFkZDRhZWVhMGRhNzcwNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o4EFua65vuKVCVxrBeP7pE6HcpcWD7S1BXyKLaA_XT4) ![Screenshot 2024-12-11 at 15 36 09](https://private-user-images.githubusercontent.com/19184658/394643601-c57c2ad5-eb85-4a32-829f-0e3760c62160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDc0ODMsIm5iZiI6MTczMzkwNzE4MywicGF0aCI6Ii8xOTE4NDY1OC8zOTQ2NDM2MDEtYzU3YzJhZDUtZWI4NS00YTMyLTgyOWYtMGUzNzYwYzYyMTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA4NTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YzcwNjc0NWNjNzU0MGE1NWI2NmFkYzQyMTNkM2FlOGEwZjAyMmE1NDNlMzNjNzgyNjFmMzliYzdiNDc1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I5pmVu30vclIU1g63f9DNFFGub7Ij4EuSqWVCm7ZnMI)

I think u should logout your account -> login with another account have free request -> close cursor -> run file .exe (by admin) -> open cusor.

I try it then success. I hope it work for u.

**Comment by hauchu1196** [comment]
@NguyenManhThuyen123 Thank you so much! I tried your method, and it worked perfectly. I really appreciate your helpful advice! 😊
