### ISSUE TITLE
curl: (56) The requested URL returned error: 404

### ISSUE THREAD

**Issue by loqmanali** [yuaotian/go-cursor-help#12]
curl: (56) The requested URL returned error: 404
Error/错误: Failed to download binary/下载二进制文件失败

Mac M1 Max

**Comment by qianyilun** [comment]
Same issue:

`curl: (22) The requested URL returned error: 404`

**Comment by zhqqqy** [comment]
看样子是改名字了，叫cursor_id_modifier_v2.0.0_mac_m1 。名字没统一

**Comment by loqmanali** [comment]
> Fixed it, use the following bash
> 
> curl -fsSL https://raw.githubusercontent.com/yuaotian/go-cursor-help/refs/heads/master/install.sh | sudo bash

Thank you it's working fine
