### ISSUE TITLE
执行sudo cursor-id-modifier报错

### ISSUE THREAD

**Issue by oneboy232** [yuaotian/go-cursor-help#13]
/usr/local/bin/cursor-id-modifier: line 7: syntax error near unexpected token `newline'
/usr/local/bin/cursor-id-modifier: line 7: `<!DOCTYPE html>'

Apple M3 pro芯片

**Comment by yuaotian** [comment]
修复了哦，下面是最新的
curl -fsSL https://raw.githubusercontent.com/yuaotian/go-cursor-help/refs/heads/master/install.sh | sudo bash
