### ISSUE TITLE
hi, can it make cursor tab to be useful?

### ISSUE THREAD

**Issue by tian-2024** [yuaotian/go-cursor-help#16]
![image](https://github.com/user-attachments/assets/af8c5b75-7ece-4373-934e-9afe5f00a73f)

HI, thank you for your great work~ I tired this tool but cursor tab still needs pro.

**Comment by yuaotian** [comment]
This is caused by the cursor itself, maybe your trial period has expired, you can change the trumpet or upgrade the pro to try~

**Comment by dacrab** [comment]
no , its for bypass the error you get when you connect with many accounts "Too many free trial accounts used on this machine. Please upgrade to pro. We have this limit in place to prevent abuse. Please let us know if you believe this is a mistake."

**Comment by tian-2024** [comment]
> no , its for bypass the error you get when you connect with many accounts "Too many free trial accounts used on this machine. Please upgrade to pro. We have this limit in place to prevent abuse. Please let us know if you believe this is a mistake."

oh I see, thank you~
