### ISSUE TITLE
Restart cursor in ubuntu

### ISSUE THREAD

**Issue by nhamtrieu** [yuaotian/go-cursor-help#17]
How can i restart cursor appimage application in ubuntu
![image](https://github.com/user-attachments/assets/aea8481a-77b7-4cf2-a434-f688650bc51b)
![image](https://github.com/user-attachments/assets/d322d805-d693-4db7-a70b-c69db8b31083)

**Comment by dacrab** [comment]
you should be fine with just closing and re-opening the app
