### ISSUE TITLE
[Windows 11] Unexpected error: exec: "whoami": executable file not found in %PATH%

### ISSUE THREAD

**Issue by idMJA** [yuaotian/go-cursor-help#25]
Any ideas for this?

![image](https://github.com/user-attachments/assets/296ece6d-939a-45a2-9d43-5d7a1dc8dc55)

**Comment by joooy94** [comment]
我成功了

**Comment by Lauorie** [comment]
我也成功了

**Comment by yuaotian** [comment]
You need to add the %PATH% environment variable and include the directory [C:\Windows\System32], or rather [C:\Windows\System32\whoami.exe].
