### ISSUE TITLE
Cursor 目录下没有 User 文件夹，是什么问题？

### ISSUE THREAD

**Issue by yuzhounh** [yuaotian/go-cursor-help#29]
**Manual Method 中提到：**
Windows: %APPDATA%\Cursor\User\globalStorage\storage.json

**但我的 Cursor 目录下没有 User 文件夹**
PS C:\Users\{Name}\AppData\Local\Programs\cursor> dir

    目录: C:\Users\{Name}\AppData\Local\Programs\cursor

| Mode | LastWriteTime | Length | Name |
|------|--------------|---------|------|
| d----- | 2024/12/10 17:22 | | locales |
| d----- | 2024/12/10 17:22 | | resources |
| -a---- | 2024/12/6 14:05 | 150,045 | chrome_100_percent.pak |
| -a---- | 2024/12/6 14:05 | 225,418 | chrome_200_percent.pak |
| -a---- | 2024/12/6 14:05 | 177,057,024 | Cursor.exe |
| -a---- | 2024/12/6 14:05 | 367 | Cursor.VisualElementsManifest.xml |
| -a---- | 2024/12/6 14:05 | 4,916,728 | d3dcompiler_47.dll |
| -a---- | 2024/12/6 14:05 | 2,692,608 | ffmpeg.dll |
| -a---- | 2024/12/6 14:05 | 10,717,680 | icudtl.dat |
| -a---- | 2024/12/6 14:05 | 480,768 | libEGL.dll |
| -a---- | 2024/12/6 14:05 | 7,960,064 | libGLESv2.dll |
| -a---- | 2024/12/6 14:05 | 1,096 | LICENSE.electron.txt |
| -a---- | 2024/12/6 14:05 | 10,272,193 | LICENSES.chromium.html |
| -a---- | 2024/12/6 14:05 | 5,350,667 | resources.pak |
| -a---- | 2024/12/6 14:05 | 307,974 | snapshot_blob.bin |
| -a---- | 2024/12/6 14:06 | 182,392 | Uninstall Cursor.exe |
| -a---- | 2024/12/6 14:05 | 656,953 | v8_context_snapshot.bin |
| -a---- | 2024/12/6 14:05 | 5,372,928 | vk_swiftshader.dll |
| -a---- | 2024/12/6 14:05 | 106 | vk_swiftshader_icd.json |
| -a---- | 2024/12/6 14:05 | 957,440 | vulkan-1.dll |

**Cursor 版本如下**
Version: 0.43.6
VSCode Version: 1.93.1
Commit: a846435528b4b760494a836f96f0739889253530
Date: 2024-12-06T05:11:55.168Z
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

这是什么问题？该如何解决？

注：以下两种方法同样不起作用，输出一堆乱码。
Automatic Installation
Script Method (Alternative)

**Comment by fjjzy** [comment]
C:\Users\你的win用户名\AppData\Roaming\Cursor\User\globalStorage，看看这个

**Comment by yuzhounh** [comment]
> C:\Users\你的win用户名\AppData\Roaming\Cursor\User\globalStorage，看看这个

可以了，非常感谢
