### ISSUE TITLE
tab 自动补全消失了

### ISSUE THREAD

**Issue by chenqiant** [yuaotian/go-cursor-help#47]
为什么tab 自动补全消失了，和这个修改有关系吗？ ctrl + K , ctrl + L 都可以用的

**Comment by LemonCandyC** [comment]
同样遇到同样的问题请问是如何结局的呢

**Comment by masklong** [comment]
> 为什么tab 自动补全消失了，和这个修改有关系吗？ ctrl + K , ctrl + L 都可以用的

遇到同样的问题，请问是怎么解决的？
