### ISSUE TITLE
按照操作步骤都执行成功了，打开还是无法使用tab功能，这个功能包含破解范围内吗

### ISSUE THREAD

**Issue by zhuangjunkun** [yuaotian/go-cursor-help#65]
按照操作步骤都执行成功了，打开还是无法使用tab功能，这个功能包含破解范围内吗

**Comment by hiwurun** [comment]
我也是

**Comment by chenyuncai** [comment]
还是require pro

**Comment by yuaotian** [comment]
如果你在试用期中这个tab应该是可以使用的，但是如果不出现可能是网络问题，你可以检查一下网络比如代理和是不是关闭配置里面的 HTTP 2.0 另外有时候cursor也会经常抽风，需要你多按几次tab才会触发，还有一种可能就是被你禁用了tab，右下角的【cursor tab】里面有开关配置
![image](https://github.com/user-attachments/assets/9afd6b13-35f0-48ce-9bdf-f8c6b09908dd)

**Comment by webskying** [comment]
不用试了，这个破解根本无法使用

**Comment by masklong** [comment]
<img width="351" alt="image" src="https://github.com/user-attachments/assets/afc4475d-20fc-4f6f-b3ec-7ddc90364352" />

您好，我提示的是
提示的是：Requires pro (custom model).
chat 功能是可以正常使用；
有没有办法修复？

> 如果你在试用期中这个tab应该是可以使用的，但是如果不出现可能是网络问题，你可以检查一下网络比如代理和是不是关闭配置里面的 HTTP 2.0 另外有时候cursor也会经常抽风，需要你多按几次tab才会触发，还有一种可能就是被你禁用了tab，右下角的【cursor tab】里面有开关配置 ![image](https://private-user-images.githubusercontent.com/50616060/397641822-9afd6b13-35f0-48ce-9bdf-f8c6b09908dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDI3ODYsIm5iZiI6MTczNDk0MjQ4NiwicGF0aCI6Ii81MDYxNjA2MC8zOTc2NDE4MjItOWFmZDZiMTMtMzVmMC00OGNlLTliZGYtZjhjNmIwOTkwOGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDA4MjgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNjYxYmE5ZTU4MjMwNGVhOWZlNGZlZGQ5M2I0NjY1ZTQzOGJlYjNmZDc3MTg3YTZjZjdkOWU2NjNiNjZlMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XIKclYkBf0GGY-8JR1ywMM6heTNnu7O-2abjhjCi6ek)

**Comment by qazwyw** [comment]
> 您好，我提示的是
> 提示的是：Requires pro (custom model).
> chat 功能是可以正常使用；
> 有没有办法修复？

您好，我跟楼上兄弟一模一样，也是提示：Requires pro (custom model).
chat 功能是可以正常使用；
有没有办法修复？
![image](https://github.com/user-attachments/assets/0a7454c5-e8f8-4e8e-8631-839fe193212d)

**Comment by masklong** [comment]
> > 您好，我提示的是
> > 提示的是：Requires pro (custom model).
> > chat 功能是可以正常使用；
> > 有没有办法修复？
> 
> 您好，我跟楼上兄弟一模一样，也是提示：Requires pro (custom model). chat 功能是可以正常使用； 有没有办法修复？ ![image](https://private-user-images.githubusercontent.com/9583838/398304075-0a7454c5-e8f8-4e8e-8631-839fe193212d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMzAwOTMsIm5iZiI6MTczNTAyOTc5MywicGF0aCI6Ii85NTgzODM4LzM5ODMwNDA3NS0wYTc0NTRjNS1lOGY4LTRlOGUtODYzMS04MzlmZTE5MzIxMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMDg0MzEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjhjZDczZTFkOTAzMzMyODdlMGRmNzI2ODczNjUzNzIyNzhhZWFkYTEzMzhkODkxZTgwZTkxZjFlODk1NmVjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.iPfI9HCjRJhtz4azRd0obZhwGVuItb1wE1Dd6kYI_Bw)

我通过下面步骤，解决了：
1. 卸载cursor，并重新安装
2. 使用工具重新修改机器码
3. 重新注册试用账号并登陆
4. 退出cursor，重新打开项目 tab 功能正常

**Comment by 2631916218** [comment]
大佬，我也是同样遇到了tab提示：Requires pro (custom model). chat可以正常使用，这个有解决方案嘛？

**Comment by zhuangjunkun** [comment]
来了，兄弟们，删除试用期过期的账户，重新注册登录（我是用github一键登录，删完了再一键登录直接刷新），这个工具是破解机器识别的，一个设备默认是允许三个使用账户体验，这个工具是破解这个限制 。两个组合使用

**Comment by HUMINGHAO05** [comment]
大佬 想问一下为什么我的下面是这样的

<img width="123" alt="Image" src="https://github.com/user-attachments/assets/f188731f-173c-45fe-abf2-e555b4761619" />
