### ISSUE TITLE
Mac已经失效

### ISSUE THREAD

**Issue by bytemaker-io** [yuaotian/go-cursor-help#84]
Mac已经失效

**Comment by bytemaker-io** [comment]
mac的cursor似乎有自动更新。自动更新后，本工具自动失效。windows没更新的cursor仍然正常

**Comment by 2arch** [comment]
are you sure

**Comment by Coldmooon** [comment]
我在 MAC 上刚试了，仍然有效。

**Comment by yuaotian** [comment]
如果你觉得他的更新很恶心，试一下，下面的操作，我目前就是这样，Windows目前可用~其他系统可以参考试一下

禁止更新（Win）：
打开文件资源管理器, 定位下面的地址:
%USERPROFILE%\AppData\Local\cursor-updater\
1、cursor-updater 文件夹删掉
2、新建一个文件去掉后缀取名【cursor-updater】占用这个文件夹名，**这样就不会在里面下新版文件咯，进行强制更新**
![image](https://github.com/user-attachments/assets/04be7a0c-ac34-460d-a6aa-2cc9141847d1)

官网下载新版：https://www.cursor.com/downloads
第三方历史版本：https://downloader-cursor.deno.dev/

参考：
https://linux.do/t/topic/298604
https://linux.do/t/topic/297886

**Comment by pianfang** [comment]
我的 MAC 上也失效了

**Comment by caohui-net** [comment]
重新装回到0.42.5，也没有效果，仍是原来的计数。关闭了应用，logout出了账号，还有哪里不对吧？

**Comment by panhongfeng** [comment]
是的 mac 的已经失效了。
版本: 0.44.9
提交: 1.93.1
日期: 316e524257c2ea23b755332b0a72c50cf23e1b00
Electron: 2024-12-26T21:58:59.149Z
ElectronBuildId: 30.5.1
Chromium: undefined
Node.js: 124.0.6367.243
V8: 20.16.0
OS: 12.4.254.20-electron.0

**Comment by bytemaker-io** [comment]
Rerun the tracker and set it immutable.


sudo chmod 444 storage.json
chflags uchg storage.json
