### ISSUE TITLE
doesent work for Mac OS

### ISSUE THREAD

**Issue by mmmahne** [yuaotian/go-cursor-help#87]
![image](https://github.com/user-attachments/assets/18bd6299-4aa5-4750-a784-81f16fd318d9)

**Comment by RectorPh** [comment]
Me too, are there any updates yet?

**Comment by mmmahne** [comment]
> Me too, are there any updates yet?


it worked use chmod first

**Comment by debarsh1** [comment]
> > Me too, are there any updates yet?
> 
> it worked use chmod first

can you please help me how to use the chmod please

**Comment by mmmahne** [comment]
> > > Me too, are there any updates yet?
> > 
> > 
> > it worked use chmod first
> 
> can you please help me how to use the chmod please

https://github.com/yuaotian/go-cursor-help/issues/78
